apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ots3"
  annotations:
    grafana/dashboard-selector: 'tag:gitlab-ci-jobs'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
